// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNa10W3VKiCGuzLkT83_Itg3tzDuw7Scw',
    appId: '1:892033678928:web:3b974dc68ee7fe39009b55',
    messagingSenderId: '892033678928',
    projectId: 'natural-client-418503',
    authDomain: 'natural-client-418503.firebaseapp.com',
    storageBucket: 'natural-client-418503.appspot.com',
    measurementId: 'G-CZX59CXS92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0v6p7f6FeafE4jauFyw9GKsSnq1AW_xk',
    appId: '1:892033678928:android:2f9b920568060616009b55',
    messagingSenderId: '892033678928',
    projectId: 'natural-client-418503',
    storageBucket: 'natural-client-418503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXjNilljN7ar21VDv-vd5qLgF8buoE-KY',
    appId: '1:892033678928:ios:ee7e4d44a6cd0a30009b55',
    messagingSenderId: '892033678928',
    projectId: 'natural-client-418503',
    storageBucket: 'natural-client-418503.appspot.com',
    iosClientId:
        '892033678928-ildcapn15fg00cahgtcse3c3lrj72f9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.budy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXjNilljN7ar21VDv-vd5qLgF8buoE-KY',
    appId: '1:892033678928:ios:d163fc706c48fcd0009b55',
    messagingSenderId: '892033678928',
    projectId: 'natural-client-418503',
    storageBucket: 'natural-client-418503.appspot.com',
    iosClientId:
        '892033678928-18jp1qj1aekkgl1lqmpet8h00k29gbb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.budy.RunnerTests',
  );
}
