// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS9vjjDzFM8-iocWUGp0CiWbKoBlddnsg',
    appId: '1:523373871783:web:ba28e62ad8ae8ced411182',
    messagingSenderId: '523373871783',
    projectId: 'budyapp-a1a1f',
    authDomain: 'budyapp-a1a1f.firebaseapp.com',
    storageBucket: 'budyapp-a1a1f.appspot.com',
    measurementId: 'G-872V08JBK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSpOlnbublbYmHI_SmwL_dIcRZJZE_HqE',
    appId: '1:523373871783:android:11b2f3f314f34c49411182',
    messagingSenderId: '523373871783',
    projectId: 'budyapp-a1a1f',
    storageBucket: 'budyapp-a1a1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAblsoJXXc-lQhkO218KnjvJeeIhmnGCo8',
    appId: '1:523373871783:ios:3dcdd1223e467af4411182',
    messagingSenderId: '523373871783',
    projectId: 'budyapp-a1a1f',
    storageBucket: 'budyapp-a1a1f.appspot.com',
    iosBundleId: 'com.example.budy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAblsoJXXc-lQhkO218KnjvJeeIhmnGCo8',
    appId: '1:523373871783:ios:38c9705531f919c0411182',
    messagingSenderId: '523373871783',
    projectId: 'budyapp-a1a1f',
    storageBucket: 'budyapp-a1a1f.appspot.com',
    iosBundleId: 'com.example.budy.RunnerTests',
  );
}
